---
- hosts: all
  vars:
    mi_usuario: redhat
    mi_password: $6$4zWt9XRtfVzoz0zl$a3R8xa95AWiWllSheaUND.XtGM.XkjKPgd/yDXXBMxAXphb6o5Mk23ZXMIzMw4cXoNjJtbJHsDZ4jnbBJtAPS/

  tasks:
    - name: Modificar la contraseña de un usuario
      user:
        name: "{{ mi_usuario }}"
        password: "{{ 'mi_password' | password_hash('sha512') }}"
